name: Assembly Notify

on:
  schedule:
    # Every 5 minutes
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  monitor:

    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - name: Run Monitor
        run: java -jar target/*.jar